apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app1
  namespace: argocd
  labels:
    ed: subed1
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "2"
    test: "test"
spec: 
  destination: 
    namespace: app1
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbook
    repoURL: "https://github.com/swaragade/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    # automated:
    #   allowEmpty: true
    syncOptions:
      - CreateNamespace=true
